// SPEC: Part IX — Post, Crew, CrewMembership, Message, Reaction, GamificationState, Pause, Report, Block as MongoDB
// documents. Field notes carry the invariant they serve. T009.
import type { ObjectId } from "mongodb";
import type { DayKey } from "@/lib/documents";

export interface PostDoc {
  _id: ObjectId;
  clientId: string;
  userId: ObjectId;
  // A14 (2026-09-09): a standalone cardio log is its OWN post type. Before this it wrote "workout", so every count of
  // workouts silently included walks. This is a DISPLAY/ANALYSIS type only — the gamification engine's PostKind stays
  // "workout" | "meal" | "text" and a cardio post maps to "workout" at the boundary (gamification-store.ts), so XP, the
  // streak and V24/V25/V26/V30/V31 are byte-identical to before. Ritual equality, not magnitude equality (§5).
  type: "workout" | "cardio" | "meal" | "text";
  sessionId: ObjectId | null;
  photoKey: string | null; // never editable (E3)
  caption: string; // ≤ captionMaxChars
  mealTag: "breakfast" | "lunch" | "dinner" | "snack" | null;
  crewId: ObjectId | null; // the crew it was shared to at creation; null = journal only
  dayKey: DayKey; // server clock (E15); fixed at creation (V10)
  isPlannedDay: boolean; // stamped at creation so recompute equals apply (V36 note)
  workoutCompleted: boolean;
  earlierToday: boolean; // same-day backfill label (Flow 4)
  summary?: string; // A6: one readable line set by the server at workout completion ("Push day · 12/12 sets · 44 min", "Walk · 25 min · 2.1 km")
  createdAt: Date;
  deletedAt: Date | null; // post ≠ log (E3)
}

export interface CrewDoc {
  _id: ObjectId;
  name: string; // ≤ crewNameMaxChars
  emoji: string;
  captainId: ObjectId;
  inviteToken: string; // unique; regenerated by the Captain
  createdAt: Date;
  archivedAt: Date | null; // last-one-out archives silently (E2)
}

export interface CrewMembershipDoc {
  _id: ObjectId;
  crewId: ObjectId;
  userId: ObjectId; // UNIQUE per user — one crew per user
  joinedAt: Date;
  joinedDayKey: DayKey; // membership as of each day (V40)
  mutedAt: Date | null;
}

export interface MessageDoc {
  _id: ObjectId;
  clientId: string;
  crewId: ObjectId;
  userId: ObjectId;
  kind: "message" | "system"; // system lines: "Jordan joined the crew"
  body: string; // ≤ chatMessageMaxChars
  createdAt: Date;
  deletedAt: Date | null; // tombstone (E20)
}

export interface ReactionDoc {
  _id: ObjectId;
  targetType: "post";
  targetId: ObjectId;
  userId: ObjectId; // UNIQUE per user-target
  emoji: string; // ∈ reactionEmojis
  dayKey: DayKey; // for the daily XP cap (V27)
  createdAt: Date;
}

export interface GamificationStateDoc {
  _id: ObjectId;
  userId: ObjectId; // UNIQUE
  currentStreak: number;
  longestStreak: number;
  totalXP: number;
  level: number;
  shields: number; // ≤ maxShields
  lastCountedDayKey: DayKey | null;
  earnedAchievementIds: string[]; // survive undo (V35)
  recomputedAt: Date;
}

export interface PauseDoc {
  _id: ObjectId;
  userId: ObjectId;
  startDay: DayKey;
  endDay: DayKey; // return day, exclusive; ≤ start + pauseMaxDays
  createdAt: Date;
}

export interface ReportDoc {
  _id: ObjectId;
  targetType: "post" | "message" | "crewName" | "user";
  targetId: ObjectId;
  reporterId: ObjectId;
  reason: string;
  status: "open" | "resolved";
  createdAt: Date;
}

export interface BlockDoc {
  _id: ObjectId;
  blockerId: ObjectId;
  blockedId: ObjectId; // UNIQUE pair
  createdAt: Date;
}
